### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3 for 'concat_6' (op: 'Concat')

### ISSUE THREAD

**Issue by evaliyev** [sugyan/tf-embedding-visualization-demo#2]
Hi!
Thank you for your demo, it's really helpful. I tried to reuse your code (see below) and got following error.
I couldn't figure out the reason, please help.
```
Traceback (most recent call last):
  File "tsne.py", line 71, in <module>
    rows.append(tf.concat(1, images[i * size:(i + 1) * size]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1005, in concat
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 438, in _concat
    values=values, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3 for 'concat_6' (op: 'Concat') with input shapes: [], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,1], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3], [100,100,3].
```

``` python 
import math
import os

import numpy as np
import tensorflow as tf
from tensorflow.contrib.tensorboard.plugins import projector
from tensorflow.models.image.imagenet import classify_image

IMAGE_DIR = 'images'
LOG_DIR = 'logs'

classify_image.FLAGS = tf.app.flags.FLAGS
tf.app.flags.DEFINE_string('model_dir', '/tmp/imagenet', """Path to model.""")

classify_image.maybe_download_and_extract()
classify_image.create_graph()
basedir = os.path.dirname(__file__)

with tf.Session() as sess:
    pool3 = sess.graph.get_tensor_by_name('pool_3:0')

    jpeg_data = tf.placeholder(tf.string)
    thumbnail = tf.cast(tf.image.resize_images(tf.image.decode_jpeg(jpeg_data), [100, 100]), tf.uint8)
    #thumbnail = sess.graph.get_tensor_by_name('ResizeBilinear:0')

    outputs = []
    files = []
    images = []

    logs_path = os.path.join(basedir, LOG_DIR)
    if not os.path.exists(logs_path):
        os.makedirs(logs_path)

    # link metadata
    metadata_path = os.path.join(basedir, LOG_DIR, 'metadata.tsv')
    metadata = open(metadata_path, 'w')

    for folder_name in os.listdir(IMAGE_DIR):
        for file_name in os.listdir(IMAGE_DIR + '/' + folder_name):
            if not file_name.endswith('.jpg'):
                continue
            print('process %s...' % file_name)
            # files.append(file_name)
            with open(os.path.join(basedir, IMAGE_DIR + '/' + folder_name, file_name), 'rb') as f:
                data = f.read()
                results = sess.run([pool3, thumbnail], {'DecodeJpeg/contents:0': data, jpeg_data: data})
                #results = sess.run([thumbnail], {'DecodeJpeg/contents:0': data})
                outputs.append(results[0])
                images.append(results[1])
                #images.append(results)
                metadata.write('{}\t{}\n'.format(file_name, folder_name))

    metadata.close()           
    embedding_var = tf.Variable(tf.pack([tf.squeeze(x) for x in outputs], axis=0), trainable=False, name='pool3')
    # prepare projector config
    config = projector.ProjectorConfig()
    embedding = config.embeddings.add()
    embedding.tensor_name = embedding_var.name
    summary_writer = tf.summary.FileWriter(os.path.join(basedir, LOG_DIR))
    
    # link metadata
    embedding.metadata_path = metadata_path
    # write to sprite image file
    image_path = os.path.join(basedir, LOG_DIR, 'sprite.jpg')
    size = int(math.sqrt(len(images))) + 1

    while len(images) < size * size:
        images.append(np.zeros((100, 100, 3), dtype=np.uint8))
    rows = []
    for i in range(size):
        rows.append(tf.concat(1, images[i * size:(i + 1) * size]))
    jpeg = tf.image.encode_jpeg(tf.concat(0, rows))
    with open(image_path, 'wb') as f:
        f.write(sess.run(jpeg))
    embedding.sprite.image_path = image_path
    embedding.sprite.single_image_dim.extend([100, 100])
    # save embedding_var
    projector.visualize_embeddings(summary_writer, config)
    sess.run(tf.variables_initializer([embedding_var]))
    saver = tf.train.Saver([embedding_var])
    saver.save(sess, os.path.join(basedir, LOG_DIR, 'model.ckpt'))```

**Comment by sugyan** [comment]
oh.. are you using grayscale image?
`tf.image.decode_jpeg` may return tensor with channel=1 automatically when content is grayscale image.
So, it may be resolved by changing it as follows.

```diff
-    thumbnail = tf.cast(tf.image.resize_images(tf.image.decode_jpeg(jpeg_data), [100, 100]), tf.uint8)
+    thumbnail = tf.cast(tf.image.resize_images(tf.image.decode_jpeg(jpeg_data, channels=3), [100, 100]), tf.uint8)
```

Thanks.

**Comment by evaliyev** [comment]
Thank you for so quick response. I have 5032 color images separated into folder by class.

**Comment by sugyan** [comment]
Well ... But, according to the error message you pasted, it contains `[100, 100, 1]`, right? I think that this is decoded as an image with channels = 1.
Could you please check the shape of `results` for each image?

**Comment by evaliyev** [comment]
You are right. For some images ```results[1].shape ``` is ```(100,100,1)```.  However, your snippet worked! Thanks!

**Comment by sachsom** [comment]
I am doing for diffrent images an i did the second code to get the h5 file now when i run the 3rd fine tuning code i get this error

ValueError: Dimension 1 in both shapes must be equal, but are 1 and 2 for 'Assign_366' (op: 'Assign') with input shapes: [256,1], [256,2].
